export default function Head() {
  return (
    <>
      <title>Long Tran Decor</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon.ico" />
      <meta name="theme-color" content="#ff007a" />
      <meta name="og:title" content="Long Tran Decor" />
      <meta name="og:image" content="/images/favicon.ico" />
      <meta name="og:description" content="Long Tran Decor" />
      <meta name="keywords" content="Long Tran Decor" />
      <meta name="renderer" content="webkit" />
      <meta name="title" content="Long Tran Decor" />
      <meta name="image" content="/images/favicon.ico" />
      <meta name="description" content="Long Tran Decor" />
      <meta name="format-detection" content="email=no" data-shuvi-head="true" />
      <meta name="apple-mobile-web-app-status-bar-style" content="black" data-shuvi-head="true" />
      <meta name="apple-mobile-web-app-capable" content="yes" data-shuvi-head="true" />
      <meta name="keywords" content="Long Tran Decor" data-shuvi-head="true" />
      <link rel="apple-touch-icon" type="image/png" href="/images/favicon.ico" />
      <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
      <link rel="icon" type="image/png" href="/images/favicon.ico" />
      <link rel="canonical" href="https://long-decor.vercel.app/" data-shuvi-head="true" />
      <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico" data-shuvi-head="true" />
      <meta property="og:site_name" content="Long Tran Decor" data-shuvi-head="true" />
      <meta property="og:title" content="Long Tran Decor" data-shuvi-head="true" />
      <meta property="og:type" content="website" data-shuvi-head="true" />
      <meta property="og:url" content="https://long-decor.vercel.app/" data-shuvi-head="true" />
      <meta property="og:image" content="/images/favicon.ico" data-shuvi-head="true" />
      <meta property="og:description" content="Long Tran Decor" />
    </>
  );
}
